# Copyright 2024 Antmicro
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
  workflow_call:
    inputs:
      cores:
        required: true
        type: string
      machtype:
        required: true
        type: string

jobs:
  run_matrix:
    strategy:
      fail-fast: false
      matrix:
        designs: [ibex, tinyRocket, black_parrot]
        cores: ${{ fromJson(inputs.cores) }}
    runs-on: [self-hosted, Linux, X64]
    container: debian:bullseye-slim
    env:
      GHA_MACHINE_TYPE: ${{ inputs.machtype }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: workspace-tarball-${{ matrix.designs }}
      - name: untar workspace
        shell: bash
        run: |
          tar xvf workspace-${{ matrix.designs }}.tar
      - name: run
        shell: bash
        run: |
          echo "DESIGN: "
          echo ${{ matrix.designs }}
          echo "Cores: "
          echo ${{ matrix.cores }}
          ./apt_install.sh
          pip3 install --user tqdm
          echo "Starting benchmark"
          # Saving previous states of LD_LIBRARY_PATH saves the environment's defaults
          # from being overridden, in CI it avoids linking errors
          export LD_LAST_PATH=$LD_LIBRARY_PATH
          source ./dependencies/env.sh
          export LD_LIBRARY_PATH=$LD_LAST_PATH:$LD_LIBRARY_PATH
          python3 benchmark_multithreaded.py ${{ matrix.designs }} ${{ matrix.cores }}
          tar cvf output-${{ matrix.designs }}_${{ matrix.cores }}.tar ./output_${{ matrix.designs }}
      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.designs }}-${{ matrix.cores }}
          path: |
            output-${{ matrix.designs }}_${{ matrix.cores }}.tar
